name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: codfish/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        plugins: "['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github']"