name: test

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'  # Replace with your Go version

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: go test .